### ISSUE TITLE
Meerdere tegelijk opvragen werkt alleen bij /tpc

### ISSUE THREAD

**Issue by koch-t** [StichtingOpenGeo/Koppelvlakken#3]
Als ik kijk naar kv78turbo-demo.py zou het behalve voor /tpc ook voor de rest het mogelijk moeten zijn om bijvoorbeeld
"/line/GVB_5_1,GVB_5_2" op te vragen. Alleen de eerste key word beantwoord.
Usecase die ik heb voor deze functionaliteit is om te kijken een lijn 1 of 2  richting(en) heeft.

**Comment by skinkie** [comment]
Ik heb geen druppel aan de code aangepast, alleen herstart. En nu werkt het wel. Dus ik ben erg benieuwd of het een bug is of dat het eigenlijk al werkte, maar geen lijnen zonder data toonde.

**Comment by skinkie** [comment]
Kun jij het ticket sluiten als jij hem ook werkend ziet? Of een manier hebt om het opnieuw te reproduceren?

**Comment by koch-t** [comment]
Werkt inderdaad. Achteraf heb ik het gevoel dat het ook niet werkte bij /tpc, weinig bussen etc. Zal ticket weer openen of/als het weer optreed.
